# permissions for end users to edit operatorwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorwatcher-editor-role
rules:
- apiGroups:
  - operator.alauda.io
  resources:
  - operatorwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.alauda.io
  resources:
  - operatorwatchers/status
  verbs:
  - get
