# permissions for end users to edit operatorstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorstatus-editor-role
rules:
- apiGroups:
  - operator.alauda.io
  resources:
  - operatorstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.alauda.io
  resources:
  - operatorstatuses/status
  verbs:
  - get
