
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: operatorwatchers.operator.alauda.io
spec:
  group: operator.alauda.io
  names:
    kind: OperatorWatcher
    listKind: OperatorWatcherList
    plural: operatorwatchers
    singular: operatorwatcher
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OperatorWatcher is the Schema for the operatorwatchers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OperatorWatcherSpec defines the desired state of OperatorWatcher
          type: object
        status:
          description: OperatorWatcherStatus defines the observed state of OperatorWatcher
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
